on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: tox test
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Checkout
        uses: actions/checkout@v2
      - name: Tox Action Step
        id: tox
        uses: paolorechia/pox@v1.0
        with:
          tox_env: 'py38-mode-unit'
      - name: Get the output success flag
        run: |
          echo "Tests have passed: ${{ steps.tox.outputs.success_flag }}"